### ISSUE TITLE
UI controls overlapped by content, not usable

### ISSUE THREAD

**Issue by mirabilos** [CuppaZee/Legacy#133]
**Describe the bug**
In (at least) the Universal Capper, UI elements are overlapping and therefore unusable.

**To Reproduce**
1. Go to the Universal Capper

**Expected behavior**
UI elements scale, scroll and reposition so that everything can be used.

**Screenshots**
![mildly censored screenshot](https://github.com/CuppaZee/Legacy/assets/861078/7c80fef0-9603-4e8e-805a-b62ef33f5eb7)

**Smartphone (please complete the following information):**
 - Device: iPhone SE
 - OS: iOS 15.8
 - Browser: no
 - Version: 2.1

**Comment by sohcah** [comment]
We no longer provide support via GitHub - in the future, please report issues via official channels listed at https://cuppazee.com/contact

We're aware there are UI issues in CuppaZee Max's Universal Capper - they are unlikely to be fixed.
The new UI in CuppaZee V3 should avoid these issues - we're aiming to release the new Universal Capper UI to the V3 app this Friday if all goes to plan.
